INSERT INTO public.towns (slug, name, full_name, county) VALUES
  ('allendale',          'Allendale',          'Borough of Allendale',           'Bergen'),
  ('alpine',             'Alpine',              'Borough of Alpine',              'Bergen'),
  ('bergenfield',        'Bergenfield',         'Borough of Bergenfield',         'Bergen'),
  ('bogota',             'Bogota',              'Borough of Bogota',              'Bergen'),
  ('carlstadt',          'Carlstadt',           'Borough of Carlstadt',           'Bergen'),
  ('cliffside-park',     'Cliffside Park',      'Borough of Cliffside Park',      'Bergen'),
  ('closter',            'Closter',             'Borough of Closter',             'Bergen'),
  ('cresskill',          'Cresskill',           'Borough of Cresskill',           'Bergen'),
  ('demarest',           'Demarest',            'Borough of Demarest',            'Bergen'),
  ('dumont',             'Dumont',              'Borough of Dumont',              'Bergen'),
  ('east-rutherford',    'East Rutherford',     'Borough of East Rutherford',     'Bergen'),
  ('edgewater',          'Edgewater',           'Borough of Edgewater',           'Bergen'),
  ('elmwood-park',       'Elmwood Park',        'Borough of Elmwood Park',        'Bergen'),
  ('emerson',            'Emerson',             'Borough of Emerson',             'Bergen'),
  ('englewood-cliffs',   'Englewood Cliffs',    'Borough of Englewood Cliffs',    'Bergen'),
  ('fair-lawn',          'Fair Lawn',           'Borough of Fair Lawn',           'Bergen'),
  ('fairview',           'Fairview',            'Borough of Fairview',            'Bergen'),
  ('fort-lee',           'Fort Lee',            'Borough of Fort Lee',            'Bergen'),
  ('franklin-lakes',     'Franklin Lakes',      'Borough of Franklin Lakes',      'Bergen'),
  ('glen-rock',          'Glen Rock',           'Borough of Glen Rock',           'Bergen'),
  ('harrington-park',    'Harrington Park',     'Borough of Harrington Park',     'Bergen'),
  ('hasbrouck-heights',  'Hasbrouck Heights',   'Borough of Hasbrouck Heights',   'Bergen'),
  ('haworth',            'Haworth',             'Borough of Haworth',             'Bergen'),
  ('hillsdale',          'Hillsdale',           'Borough of Hillsdale',           'Bergen'),
  ('ho-ho-kus',          'Ho-Ho-Kus',           'Borough of Ho-Ho-Kus',           'Bergen'),
  ('leonia',             'Leonia',              'Borough of Leonia',              'Bergen'),
  ('little-ferry',       'Little Ferry',        'Borough of Little Ferry',        'Bergen'),
  ('lodi',               'Lodi',                'Borough of Lodi',                'Bergen'),
  ('maywood',            'Maywood',             'Borough of Maywood',             'Bergen'),
  ('midland-park',       'Midland Park',        'Borough of Midland Park',        'Bergen'),
  ('montvale',           'Montvale',            'Borough of Montvale',            'Bergen'),
  ('moonachie',          'Moonachie',           'Borough of Moonachie',           'Bergen'),
  ('new-milford',        'New Milford',         'Borough of New Milford',         'Bergen'),
  ('north-arlington',    'North Arlington',     'Borough of North Arlington',     'Bergen'),
  ('northvale',          'Northvale',           'Borough of Northvale',           'Bergen'),
  ('norwood',            'Norwood',             'Borough of Norwood',             'Bergen'),
  ('oakland',            'Oakland',             'Borough of Oakland',             'Bergen'),
  ('old-tappan',         'Old Tappan',          'Borough of Old Tappan',          'Bergen'),
  ('oradell',            'Oradell',             'Borough of Oradell',             'Bergen'),
  ('palisades-park',     'Palisades Park',      'Borough of Palisades Park',      'Bergen'),
  ('paramus',            'Paramus',             'Borough of Paramus',             'Bergen'),
  ('park-ridge',         'Park Ridge',          'Borough of Park Ridge',          'Bergen'),
  ('ramsey',             'Ramsey',              'Borough of Ramsey',              'Bergen'),
  ('ridgefield',         'Ridgefield',          'Borough of Ridgefield',          'Bergen'),
  ('river-edge',         'River Edge',          'Borough of River Edge',          'Bergen'),
  ('rockleigh',          'Rockleigh',           'Borough of Rockleigh',           'Bergen'),
  ('rutherford',         'Rutherford',          'Borough of Rutherford',          'Bergen'),
  ('saddle-river',       'Saddle River',        'Borough of Saddle River',        'Bergen'),
  ('tenafly',            'Tenafly',             'Borough of Tenafly',             'Bergen'),
  ('teterboro',          'Teterboro',           'Borough of Teterboro',           'Bergen'),
  ('upper-saddle-river', 'Upper Saddle River',  'Borough of Upper Saddle River',  'Bergen'),
  ('waldwick',           'Waldwick',            'Borough of Waldwick',            'Bergen'),
  ('wallington',         'Wallington',          'Borough of Wallington',          'Bergen'),
  ('westwood',           'Westwood',            'Borough of Westwood',            'Bergen'),
  ('woodcliff-lake',     'Woodcliff Lake',      'Borough of Woodcliff Lake',      'Bergen'),
  ('wood-ridge',         'Wood-Ridge',          'Borough of Wood-Ridge',          'Bergen'),
  ('lyndhurst',          'Lyndhurst',           'Township of Lyndhurst',          'Bergen'),
  ('mahwah',             'Mahwah',              'Township of Mahwah',             'Bergen'),
  ('river-vale',         'River Vale',          'Township of River Vale',         'Bergen'),
  ('rochelle-park',      'Rochelle Park',       'Township of Rochelle Park',      'Bergen'),
  ('saddle-brook',       'Saddle Brook',        'Township of Saddle Brook',       'Bergen'),
  ('south-hackensack',   'South Hackensack',    'Township of South Hackensack',   'Bergen'),
  ('teaneck',            'Teaneck',             'Township of Teaneck',            'Bergen'),
  ('washington-township','Washington Township', 'Washington Township',            'Bergen'),
  ('wyckoff',            'Wyckoff',             'Township of Wyckoff',            'Bergen'),
  ('englewood',          'Englewood',           'City of Englewood',              'Bergen'),
  ('garfield',           'Garfield',            'City of Garfield',               'Bergen'),
  ('hackensack',         'Hackensack',          'City of Hackensack',             'Bergen'),
  ('ridgefield-park',    'Ridgefield Park',     'Village of Ridgefield Park',     'Bergen'),
  ('ridgewood',          'Ridgewood',           'Village of Ridgewood',           'Bergen')
ON CONFLICT (slug) DO NOTHING;